### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [ffossum/koa-example#1]
this code:

``` js
 db.tx(t => {
    const q1 = t.none('INSERT INTO games(id, host) VALUES ($(gameId), $(host))', { gameId, host });
    const q2 = t.none('INSERT INTO users_games(user_id, game_id) VALUES ($(host), $(gameId))',
      { host, gameId }
    );

    return t.batch([q1, q2]);
  });
```

creates a loose promise request.

You are supposed to use `.then` + `.catch` on the result from `db.tx` ;)

**Comment by vitaly-t** [comment]
Also, given how much SQL you have, use of [QueryFile](http://vitaly-t.github.io/pg-promise/QueryFile.html) is a good idea ;)

See also: [Query Files](https://github.com/vitaly-t/pg-promise#query-files) ;)

**Comment by ffossum** [comment]
Thanks for the heads up. :) 
Nice work on pg-promise. I'm finding it very useful, especially combined with async/await.
I'll be sure to check out query files eventually.
